name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Rsync files to server
        env:
          TARGET: ${{ secrets.DEPLOY_TARGET }}
          REMOTE_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          rsync -az --delete --exclude node_modules --exclude .git --exclude .env ./ $TARGET:$REMOTE_PATH

      - name: Run docker compose on server
        env:
          TARGET: ${{ secrets.DEPLOY_TARGET }}
          REMOTE_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no $TARGET "cd $REMOTE_PATH && docker compose pull || true && docker compose up -d --build"
